language: generic

sudo: required

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - ffmpeg -hwaccels

after_success:
  - docker build -t gksrlfw/mb-server-server ./server
  - docker build -t gksrlfw/mb-server-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gksrlfw/mb-server-server
  - docker push gksrlfw/mb-server-nginx


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mb-app"
  env: "MbApp-env"
  bucket_name: elasticbeanstalk-us-east-2-407538465392
  bucket_path: "mb-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
