language: generic

sudo: required

services:
  - docker

before_install:
  - yum -y install epel-release
  - rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
  - rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
  - yum install ffmpeg

after_success:
  - docker build -t gksrlfw/mb-server-server ./server
  - docker build -t gksrlfw/mb-server-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gksrlfw/mb-server-server
  - docker push gksrlfw/mb-server-nginx


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mb-app"
  env: "MbApp-env"
  bucket_name: elasticbeanstalk-us-east-2-407538465392
  bucket_path: "mb-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
