# 노드기반
FROM node:14.15.3

WORKDIR /app

# 도커 컨테이너 안에 있는 노드 기반의 이미지에 package.json을 카피한다
COPY package.json .

RUN npm install

# RUN npm install -g pm2

ENV NODE_ENV production

EXPOSE 3000


CMD [ "npm", "start" ]
# CMD ["npm", "run", "dev"]
# CMD [ "pm2-runtime", "start", "./bin/www" ]
# CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]

COPY . .