# 나중에 도메인 할당 -> https 설정 -> nginx 등록 전부 한 뒤에 


version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server/:/app
    environment:                    
      # PROD_HOST= mysql-express.cpn1atdn34ha.us-east-2.rds.amazonaws.com
      # PROD_NAME= TEST
      # PROD_USERNAME= admin 
      # PROD_PASSWORD= password
      # PROD_PORT= 3306
      
      # PORT= 3000

      # COOKIE_SECRET= cookiesecret

      # MAIL_EMAIL= gksrlfw@naver.com
      # MAIL_PASSWORD= gksrlf784

      # JWT_SECRET= jwtsecret


      # =================================
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   command: --innodb_use_native_aio=0  
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: eksrja784$$
  #     MYSQL_DATABASE: root
