# 노드기반
FROM node:current-slim

WORKDIR /app

# 도커 컨테이너 안에 있는 노드 기반의 이미지에 package.json을 카피한다
COPY package.json .

RUN npm install

# RUN npm install -g pm2

EXPOSE 3000

CMD [ "npm", "start" ]
# CMD [ "pm2-runtime", "start", "./bin/www" ]

COPY . .